name: pr_validation

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev
  merge_group:

jobs:
  build-templates:
    name: BuildTemplate
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
        with:
          lfs: true
          fetch-depth: 0
      - name: "Install .NET SDK"
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            7.0.x
          global-json-file: "./global.json"
      - name: "dotnet pack"
        run: dotnet pack -c Release
  test:
    name: Test-${{matrix.template}}-${{matrix.os}}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        template: ["WebApiTemplate", "AkkaConsoleTemplate", "AkkaStreamsTemplate"]
        os: [ubuntu-latest, windows-latest]
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
        with:
          lfs: true
          fetch-depth: 0
      - name: "Install .NET SDK"
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            7.0.x
          global-json-file: "./global.json"
      - name: "dotnet build"
        run: dotnet build -c Release
        working-directory: src/${{matrix.template}}
      - name: "dotnet test"
        run: dotnet test -c Release
        working-directory: src/${{matrix.template}}

  docker:
    name: Docker-${{matrix.template}}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        template: ["WebApiTemplate"]
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
        with:
          lfs: true
          fetch-depth: 0
      - name: "Install .NET SDK"
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            7.0.x
          global-json-file: "./global.json"
      - name: "dotnet docker"
        run: dotnet publish --os linux --arch x64 -c Release -p:PublishProfile=DefaultContainer
        working-directory: src/${{matrix.template}}

